# Generated by Django 6.1 on 2026-08-27 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Conversa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("origem_id", models.CharField(max_length=120)),
                ("fonte", models.CharField(max_length=60)),
                ("criada_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("fonte", "origem_id"), name="conversa_unica_por_fonte"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Mensagem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordem", models.PositiveIntegerField()),
                (
                    "autor",
                    models.CharField(
                        choices=[
                            ("usuario", "Usuário"),
                            ("atendente", "Atendente"),
                            ("sistema", "Sistema"),
                        ],
                        max_length=10,
                    ),
                ),
                ("texto", models.TextField()),
                ("enviada_em", models.DateTimeField(blank=True, null=True)),
                (
                    "rotulo_pred",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("positivo", "Positivo"),
                            ("negativo", "Negativo"),
                            ("neutro", "Neutro"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("score", models.FloatField(blank=True, null=True)),
                (
                    "rotulo_real",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("positivo", "Positivo"),
                            ("negativo", "Negativo"),
                            ("neutro", "Neutro"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "conversa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mensagens",
                        to="analise.conversa",
                    ),
                ),
            ],
            options={
                "ordering": ["conversa_id", "ordem"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("conversa", "ordem"), name="ordem_unica_por_conversa"
                    )
                ],
            },
        ),
    ]
