# Generated by Django 6.1 on 2026-09-30 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analise", "0002_users"),
    ]

    operations = [
        migrations.CreateModel(
            name="RotuloEmocao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "origem",
                    models.CharField(
                        choices=[
                            ("humano", "Humano"),
                            ("llm", "LLM"),
                            ("original_dataset", "Dataset original"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "anotador",
                    models.CharField(
                        blank=True,
                        help_text="pessoa, ou modelo+prompt da LLM",
                        max_length=60,
                    ),
                ),
                ("alegria", models.BooleanField(default=False)),
                ("raiva", models.BooleanField(default=False)),
                ("tristeza", models.BooleanField(default=False)),
                ("medo", models.BooleanField(default=False)),
                ("surpresa", models.BooleanField(default=False)),
                ("nojo", models.BooleanField(default=False)),
                (
                    "intensidades",
                    models.JSONField(
                        blank=True, help_text='opcional, 0-3: {"raiva": 2}', null=True
                    ),
                ),
                (
                    "semente_id",
                    models.CharField(
                        blank=True, help_text="só para dados sintéticos", max_length=60
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "mensagem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rotulos_emocao",
                        to="analise.mensagem",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("mensagem", "origem", "anotador"),
                        name="rotulo_emocao_unico",
                    )
                ],
            },
        ),
    ]
